### ISSUE TITLE
Bewegung Schaffner

### ISSUE THREAD

**Issue by chiariii** [chiariii/MMP-LMU#4]
Der Schaffner kann sich nach rechts und links bewegen (ohne Animation).

**Comment by chiariii** [comment]
Kann sich in 4 richtungen bewegen, aber noch keine Kollision...

**Comment by chiariii** [comment]
Hört an den Enden der Platfform auf zu laufen

**Comment by thomsenj** [comment]
Bewegungsrichtung Schaffner entspricht noch nicht Schussrichtung
